### ISSUE TITLE
New release for kinetic

### ISSUE THREAD

**Issue by miguelprada** [davetcoleman/ros_control_boilerplate#30]
Would it be possible to update the released version of this package for Kinetic?

I'm using it as a sort of lightweight simulator to test some of my robot setups and I'm currently forced to check it out from source because the fix in #20 is needed for bringup setups with multiple `controller_manager`/`spawner` instances to not trigger a deadlock.

Thanks in advance!

**Comment by fmessmer** [comment]
:+1: new release would (still) be cool :wink:

**Comment by RobertWilbrandt** [comment]
Hey, i am sorry that this just sat here so long - i'll get to this soon.

**Comment by fmessmer** [comment]
thanks!

**Comment by fmessmer** [comment]
@RobertWilbrandt @davetcoleman any chance to get this release for the next kinetic sync?
(there won't be too many more before kinetic goes EOL)

**Comment by RobertWilbrandt** [comment]
I am sorry for the delay, i hoped to get this done over christmas but only got to it now. The current plan is to backport most of ```noetic-devel``` to ```kinetic-devel``` (i will do that in the next few days, #50 is the precursor to that) and then create a new release (hopefully in time for the next sync).

**Comment by fmessmer** [comment]
the recent backport changes to `kinetic-devel` broke some of the API, now the question for us is:
will there be a new release for kinetic some time soon? then we would adjust our code and use `ros_control_boilerplate` to work with the new release
in case there wont be a release, we would probably just pin the working commit and use a branch from our fork as overlay instead of `picknikrobotics/ros_control_boilerplate#kinetic-devel`

@RobertWilbrandt what are the plans for kinetic release?

**Comment by RobertWilbrandt** [comment]
I am really sorry about this. Backporting the change from ```boost::shared_ptr``` to ```std::shared_ptr``` was an oversight on my part (the problem in the failing travis run of your linked issue), i reverted it. I am aware that this is generally not a good situation, but you are absolutely right that there should be no such change right before EOL.

The plan was to do a release for kinetic soon. I pinged @JafarAbdi (who does the release) to notify him of my error so that the revert will also be part of the release. I hope this fixes your current issue so you can use the released ```ros_control_boilerplate```.

**Comment by fmessmer** [comment]
@RobertWilbrandt 
well, if using std::shared_ptr would allow us to use the same code/branch for both kinetic and noetic - we support/use both distros with our driver - that would be an acceptable addition to kinetic-devel of ros_control_boilerplate...sorry, for the back-and-forth
in fact, best case for us would be a release that'd allow us to remove the source overlay for kinetic while still using the same code for both distros linking against the respective boilerplate release...

I already prepared a patch to make our kinetic branch compatible with the std::shared_ptr version

your call to add the std commit again - before the release is out...😉

**Comment by RobertWilbrandt** [comment]
I would also prefer it if melodic and kinetic wouldn't differ in this aspect. On the other hand, i don't really think this change warrants breaking code just before EOL, and would therefore keep ```boost::shared_ptr```.

**Comment by fmessmer** [comment]
the release is out....can be closed...thanks again!
