### ISSUE TITLE
Feature: Kinetic support

### ISSUE THREAD

**Issue by ShawnSchaerer** [davetcoleman/ros_control_boilerplate#6]
Are you going to support kinetic when it comes out?

**Comment by davetcoleman** [comment]
I plan on switching to Kinetic and the new Ubuntu 16.04 soon, yes

**Comment by ShawnSchaerer** [comment]
I can help test.

**Comment by jackieokay** [comment]
A few of the Kinetic binary jobs fail for this package:

http://build.ros.org/job/Kbin_dj_dJ64__ros_control_boilerplate__debian_jessie_amd64__binary/
http://build.ros.org/job/Kbin_djv8_dJv8__ros_control_boilerplate__debian_jessie_arm64__binary/
http://build.ros.org/job/Kbin_uW32__ros_control_boilerplate__ubuntu_wily_i386__binary/

I haven't looked into the failures; they could be due to missing dependencies on the respective platforms. If that's the case, let me know and I can blacklist those packages for the particular platform.

**Comment by davetcoleman** [comment]
Looks like Eigen3 isn't being included correctly:

```
23:16:40 /opt/ros/kinetic/include/rosparam_shortcuts/rosparam_shortcuts.h:51:26: fatal error: Eigen/Geometry: No such file or directory
23:16:40  #include <Eigen/Geometry>
```

I thought I had understood how to include it in Kinetic, seems like it doesn't work on all platforms though

**Comment by davetcoleman** [comment]
I don't understand though - Travis is passing, using the rosbuild farm Travis script

**Comment by davetcoleman** [comment]
Closing this issue because kinetic has long been supported, and I'm currently releasing for Lunar
